### PR TITLE
Adding redshift database support

### PR DESCRIPTION
**Pull request by drewzboto**
Thanks for the image. Useful. Wanted to see if you would be cool with adding in Redshift....

### CODE REVIEW

**Comment by amancevice** [comment]
Depends -- for MySQL and Postgresql I needed to install some companion drivers. Does Redshift need something similar? Have you tested this?

**Comment by drewzboto** [comment]
Redshift just builds on top of the Postgres drivers, so it uses what is already in place.

I've been using my fork over the last few days to test it out. No issue so far.

**Comment by amancevice** [comment]
Okay, merged. Note that because this is an automated build the `latest` tag will have your change, but the `0.9.0` tag won't.

When AirBnB releases the next version, say `0.9.1`, then `amancevice/caravel:0.9.1` will have your change as well.

**Comment by drewzboto** [comment]
thanks!

**Pull request merged**
